#title: 
#description: 

#url: "" # your host, for absolute URL
#baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

#paginate: 1
permalink: /:slug.js

#exclude: ["less","README.md"]

markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
